name: pop_pop_win
author: Dart Team <misc@dartlang.org>
description: '"Pop, Pop, Win!" is an implementation of Minesweeper in Dart.'
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.3.0 <2.0.0'
dependencies:
  bot: any
  stagexl: any
